# Generated by Django 4.1.5 on 2023-01-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='user',
        ),
    ]
