# Generated by Django 4.1.5 on 2023-01-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todos_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todolists',
            new_name='Lists',
        ),
    ]
