# Generated by Django 4.1.5 on 2023-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_lists_date_created_todos_date_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='date_created',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='todos',
            name='datetime_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateField(editable=False),
        ),
    ]
