# Generated by Django 4.1.5 on 2023-02-07 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_lists_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='lists',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 11, 48, 52, 593392, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 11, 49, 0, 800562, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
    ]
