# Generated by Django 4.1.5 on 2023-02-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_remove_lists_date_created_remove_users_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
