# Generated by Django 4.1.5 on 2023-02-07 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_lists_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='todos',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
