# Generated by Django 4.1.5 on 2023-02-07 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_alter_lists_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todos',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
